id: P000606
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD403
  title: རྫོགས་པ་ཆེན་པོ་བསྒྲགས་པ་སྐོར་གསུམ།
  author: ''
  volumes:
    c65a74a375984e3e9995952346fa4758:
      image_group_id: I2PD18025
      title: ''
      volume_number: 1
      total_pages: 450
    a2bd5f38473244e08b182b0eccb33222:
      image_group_id: I2PD18026
      title: ''
      volume_number: 2
      total_pages: 444
