id: I550DDC8E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:57:51+00:00'
last_modified: '2022-06-07T12:26:13.400331+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD403
  title: རྫོགས་པ་ཆེན་པོ་བསྒྲགས་པ་སྐོར་གསུམ།
  author: ''
  base:
    D856:
      image_group_id: I2PD18025
      title: ''
      total_pages: 450
      order: 1
      base_file: D856.txt
    D3BB:
      image_group_id: I2PD18026
      title: ''
      total_pages: 444
      order: 2
      base_file: D3BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
